version: "3.8"

services:
  reposvc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8088"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5442
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: ["/main"]

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5442:5442"

volumes:
  postgres_data:
