version: "3.8"

services:
  reposvc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=omept
      - DB_PASSWORD=password
      - DB_NAME=reposvc_db
      - SERVER_PORT=8088
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: ["/main"]

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: omept
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reposvc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
